version: '3'

services:
  calendar:
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile.calendar
    depends_on:
      - db_migrate
    restart: always
    environment:
      CAL_HTTP_HOST: localhost
      CAL_HTTP_PORT: ${CAL_HTTP_PORT}
      CAL_GRPC_HOST: localhost
      CAL_GRPC_PORT: ${CAL_GRPC_PORT}
      CAL_STORAGE_HOST: db
      CAL_STORAGE_PORT: 5432
      CAL_STORAGE_USER: ${CAL_STORAGE_USER}
      CAL_STORAGE_PASSWORD: ${CAL_STORAGE_PASSWORD}
      CAL_STORAGE_DBNAME: ${CAL_STORAGE_DBNAME}
    ports:
      - '${CAL_HTTP_PORT}:${CAL_HTTP_PORT}'
      - '${CAL_GRPC_PORT}:${CAL_GRPC_PORT}'
    networks:
      backend:
        aliases:
          - calendar
  sheduler:
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile.scheduler
    depends_on:
      - db_migrate
      - mq
    restart: always
    environment:
      CAL_STORAGE_HOST: db
      CAL_STORAGE_PORT: 5432
      CAL_STORAGE_USER: ${CAL_STORAGE_USER}
      CAL_STORAGE_PASSWORD: ${CAL_STORAGE_PASSWORD}
      CAL_STORAGE_DBNAME: ${CAL_STORAGE_DBNAME}
      CAL_RMQ_HOST: mq
      CAL_RMQ_PORT: 5672
      CAL_RMQ_USER: ${CAL_RMQ_USER}
      CAL_RMQ_PASSWORD: ${CAL_RMQ_PASSWORD}
    networks:
      backend:
        aliases:
          - scheduler
  sender:
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile.sender
    depends_on:
      - mq
    restart: always
    environment:
      CAL_RMQ_HOST: mq
      CAL_RMQ_PORT: 5672
      CAL_RMQ_USER: ${CAL_RMQ_USER}
      CAL_RMQ_PASSWORD: ${CAL_RMQ_PASSWORD}
    networks:
      backend:
        aliases:
          - sender

