version: '3'

services:
    db:
        image: postgres:12-alpine
        restart: always
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${CAL_STORAGE_PASSWORD}
        networks:
            backend:
                aliases:
                    - db
    db_migrate:
        build:
            context: ..
            dockerfile: ./migrations/Dockerfile
        depends_on:
            - db
        environment:
            CAL_STORAGE_HOST: db
            CAL_STORAGE_PORT: 5432
            CAL_STORAGE_USER: ${CAL_STORAGE_USER}
            CAL_STORAGE_PASSWORD: ${CAL_STORAGE_PASSWORD}
            CAL_STORAGE_DBNAME: ${CAL_STORAGE_DBNAME}
        networks:
            - backend
    mq:
        image: rabbitmq:3-management-alpine
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: ${CAL_RMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${CAL_RMQ_PASSWORD}
        ports:
            - '15672:15672'
        networks:
            backend:
                aliases:
                    - mq
volumes:
    dbdata:

networks:
    backend:
        driver: bridge
