version: '3'

services:
  integration-tests:
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile.tests
    depends_on:
      - db_migrate
    environment:
      CAL_HTTP_HOST: localhost
      CAL_HTTP_PORT: ${CAL_HTTP_PORT}
      CAL_STORAGE_HOST: db
      CAL_STORAGE_PORT: 5432
      CAL_STORAGE_USER: ${CAL_STORAGE_USER}
      CAL_STORAGE_PASSWORD: ${CAL_STORAGE_PASSWORD}
      CAL_STORAGE_DBNAME: ${CAL_STORAGE_DBNAME}
    ports:
      - '${CAL_HTTP_PORT}:${CAL_HTTP_PORT}'
    networks:
      backend:
        aliases:
          - tests
  db:
    volumes:
      - dbdata_test:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  mq:
    restart: "no"
    command:
      - /bin/true
    depends_on:
      - integration-tests

volumes:
  dbdata_test:

