[logger]
level = "INFO"
log_file = ""

[server]
host = "localhost"
port = 9000
shutdown_timeout_ms = 10_000
grpc = false # if false run http rest api server

[storage]
sql = false # if false, use in-memory db
