[logger]
level = "INFO"
log_file = ""

[http]
host = "localhost"
port = 9000
shutdown_timeout_ms = 10_000

[grpc]
host = "localhost"
port = 9001

[storage]
sql = true # if false, use in-memory db
host = "localhost" # default
port = 5432 # default
user = "postgres" # default
password = "postgres" # default
dbname = "postgres" # default

[rmq]
host = "localhost" # default
port = 5672 # default
user = "guest" # default
password = "guest" # default 
exchange_name = "cal-exchange"
exchange_type = "direct" # direct|fanout|topic|x-custom
routing_key = "cal-key"
queue_name = "cal-queue"
consumer_tag = "cal-tag"

[scheduler]
interval_sec = 60